from alegra.resources.abstract.api_resource import APIResource
from alegra.resources.abstract.createable_api_resource import CreateableAPIResource
from alegra.resources.abstract.deletable_api_resource import DeleteableAPIResource 
from alegra.resources.abstract.emailable_api_resource import EmailableAPIResource
from alegra.resources.abstract.listable_api_resource import ListableAPIResource
from alegra.resources.abstract.updateable_api_resource import UpdateableAPIResource
from alegra.resources.abstract.voidable_api_resource import VoidableAPIResource
