from alegra.resources.abstract.api_resource import APIResource
from alegra.resources.abstract.listable_api_resource import ListableAPIResource
from alegra.resources.abstract.createable_api_resource import CreateableAPIResource
from alegra.resources.abstract.updateable_api_resource import UpdateableAPIResource
